[package]
name = "getting-started"
version = "0.1.0"
authors = ["박시율 <kdpark0723@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
